<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/1/18
 * Time: 16:09
 */

namespace backend\controllers;

use yii\web\Controller;


class BaseController extends Controller{

    public function auth($userId , $name){


    }

    public function beforeAction($action)
    {
        if (!$this->isLogin()){
            return  $this->redirect("/admin/user/login");
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function isLogin(){

        return false;
    }
}