/**
 * Created by NSK. on 2016/4/28/0028.
 */
var config_infoData = {
    'height': config_heightLink(140),

    'marriage': [
        {id: "1", name: '未婚'},
        {id: "2", name: '离异'},
        {id: "3", name: '丧偶'}
    ],

    'education': [
        {id: "1", name: '初中'},
        {id: "2", name: '高中'},
        {id: "3", name: '大专'},
        {id: "4", name: '本科'},
        {id: "5", name: '硕士'},
        {id: "6", name: '博士'}
    ],

    'zodiac': [
        {id: "1", name: '鼠'},
        {id: "2", name: '牛'},
        {id: "3", name: '虎'},
        {id: "4", name: '兔'},
        {id: "5", name: '龙'},
        {id: "6", name: '蛇'},
        {id: "7", name: '马'},
        {id: "8", name: '羊'},
        {id: "9", name: '猴'},
        {id: "10", name: '鸡'},
        {id: "11", name: '狗'},
        {id: "12", name: '猪'}
    ],

    'constellation': [
        {id: "1", name: '水瓶座'},
        {id: "2", name: '双鱼座'},
        {id: "3", name: '白羊座'},
        {id: "4", name: '金牛座'},
        {id: "5", name: '双子座'},
        {id: "6", name: '巨蟹座'},
        {id: "7", name: '狮子座'},
        {id: "8", name: '处女座'},
        {id: "9", name: '天秤座'},
        {id: "10", name: '天蝎座'},
        {id: "11", name: '射手座'},
        {id: "12", name: '摩羯座'}
    ],

    'children_occupation':[
        {id:1, parentId:1, name:'销售总监'},
        {id:2, parentId:1, name:'销售经理'},
        {id:3, parentId:1, name:'销售主管'},
        {id:4, parentId:1, name:'销售专员'},
        {id:5, parentId:1, name:'渠道/分销管理'},
        {id:6, parentId:1, name:'渠道/分销专员'},
        {id:7, parentId:1, name:'经销商'},
        {id:8, parentId:1, name:'客户经理'},
        {id:9, parentId:1, name:'客户代表'},
        {id:10, parentId:1, name:'其他'},
        {id: 11, parentId:2,name: 'IT技术总监'},
        {id: 12, parentId:2,name: 'IT技术经理'},
        {id: 13, parentId:2,name: 'IT工程师'},
        {id: 14, parentId:2,name: '系统管理员'},
        {id: 15, parentId:2,name: '测试专员'},
        {id: 16, parentId:2,name: '运营管理'},
        {id: 17, parentId:2,name: '网页设计'},
        {id: 18, parentId:2,name: '网站编辑'},
        {id: 19, parentId:2,name: '网站产品经理'},
        {id: 20, parentId:2,name: '其他'},
        {id: 21, parentId:3,name: '客服经理'},
        {id: 22, parentId:3,name: '客服主管'},
        {id: 23, parentId:3,name: '客服专员'},
        {id: 24, parentId:3,name: '客服协调'},
        {id: 25, parentId:3,name: '客服技术支持'},
        {id: 26, parentId:3,name: '其他'},
        {id: 27, parentId:4,name: '大一'},
        {id: 28, parentId:4,name: '大二'},
        {id: 29, parentId:4,name: '大三'},
        {id: 30, parentId:4,name: '大四'},
        {id: 31, parentId:4,name: '读研'},
        {id: 32, parentId:4,name: '读博'},
        {id: 33, parentId:4,name: '其他'},
        {id: 34, parentId:5,name: '通信技术'},
        {id: 35, parentId:5,name: '电子技术'},
        {id: 36, parentId:5,name: '其他'},
        {id: 37, parentId:6,name: '工厂经理'},
        {id: 38, parentId:6,name: '工程师'},
        {id: 39, parentId:6,name: '项目主管'},
        {id: 40, parentId:6,name: '运营经理'},
        {id: 41, parentId:6,name: '运营主管'},
        {id: 42, parentId:6,name: '车间主任'},
        {id: 43, parentId:6,name: '物料管理'},
        {id: 44, parentId:6,name: '生产领班'},
        {id: 45, parentId:6,name: '操作工人'},
        {id: 46, parentId:6,name: '安全管理'},
        {id: 47, parentId:6,name: '其他'},
        {id: 48, parentId:7,name: '物流经理'},
        {id: 49, parentId:7,name: '物流主管'},
        {id: 50, parentId:7,name: '物流专员'},
        {id: 51, parentId:7,name: '仓库经理'},
        {id: 52, parentId:7,name: '仓库管理员'},
        {id: 53, parentId:7,name: '货运代理'},
        {id: 54, parentId:7,name: '集装箱业务'},
        {id: 55, parentId:7,name: '海关事物管理'},
        {id: 56, parentId:7,name: '报单员'},
        {id: 57, parentId:7,name: '快递员'},
        {id: 58, parentId:7,name: '其他'},
        {id: 59, parentId:8,name: '商务经理'},
        {id: 60, parentId:8,name: '商务专员'},
        {id: 61, parentId:8,name: '采购经理'},
        {id: 62, parentId:8,name: '采购专员'},
        {id: 63, parentId:8,name: '外贸经理'},
        {id: 64, parentId:8,name: '外贸专员'},
        {id: 65, parentId:8,name: '业务跟单'},
        {id: 66, parentId:8,name: '报关员'},
        {id: 67, parentId:8,name: '其他'},
        {id: 68, parentId:9,name: '人事总监'},
        {id: 69, parentId:9,name: '人事经理'},
        {id: 70, parentId:9,name: '人事主管'},
        {id: 71, parentId:9,name: '人事专员'},
        {id: 72, parentId:9,name: '招聘经理'},
        {id: 73, parentId:9,name: '招聘专员'},
        {id: 74, parentId:9,name: '培训经理'},
        {id: 75, parentId:9,name: '培训专员'},
        {id: 76, parentId:9,name: '秘书'},
        {id: 77, parentId:9,name: '文员'},
        {id: 78, parentId:9,name: '后勤'},
        {id: 79, parentId:9,name: '其他'},
        {id: 80, parentId:10,name: '总经理'},
        {id: 81, parentId:10,name: '副总经理'},
        {id: 82, parentId:10,name: '合伙人'},
        {id: 83, parentId:10,name: '总监'},
        {id: 84, parentId:10,name: '经理'},
        {id: 85, parentId:10,name: '总裁助理'},
        {id: 86, parentId:10,name: '其他'},
        {id: 87, parentId:11,name: '广告客户经理'},
        {id: 88, parentId:11,name: '广告客户专员'},
        {id: 89, parentId:11,name: '广告设计经理'},
        {id: 90, parentId:11,name: '广告设计专员'},
        {id: 91, parentId:11,name: '广告策划'},
        {id: 92, parentId:11,name: '市场营销经理'},
        {id: 93, parentId:11,name: '市场营销专员'},
        {id: 94, parentId:11,name: '市场策划'},
        {id: 95, parentId:11,name: '市场调研与分析'},
        {id: 96, parentId:11,name: '市场拓展'},
        {id: 97, parentId:11,name: '公关经理'},
        {id: 98, parentId:11,name: '公关专员'},
        {id: 99, parentId:11,name: '媒介经理'},
        {id: 100, parentId:11,name: '媒介专员'},
        {id: 101, parentId:11,name: '品牌经理'},
        {id: 102, parentId:11,name: '品牌专员'},
        {id: 103, parentId:11,name: '其他'},
        {id: 104, parentId:12,name: '主编'},
        {id: 105, parentId:12,name: '编辑'},
        {id: 106, parentId:12,name: '作家'},
        {id: 107, parentId:12,name: '撰稿人'},
        {id: 108, parentId:12,name: '文案策划'},
        {id: 109, parentId:12,name: '出版发行'},
        {id: 110, parentId:12,name: '导演'},
        {id: 111, parentId:12,name: '记者'},
        {id: 112, parentId:12,name: '主持人'},
        {id: 113, parentId:12,name: '演员'},
        {id: 114, parentId:12,name: '模特'},
        {id: 115, parentId:12,name: '经纪人'},
        {id: 116, parentId:12,name: '摄影师'},
        {id: 117, parentId:12,name: '影视后期制作'},
        {id: 118, parentId:12,name: '设计师'},
        {id: 119, parentId:12,name: '画家'},
        {id: 120, parentId:12,name: '音乐家'},
        {id: 121, parentId:12,name: '舞蹈'},
        {id: 122, parentId:12,name: '其他'},
        {id: 123, parentId:13,name: '飞行员'},
        {id: 124, parentId:13,name: '空乘人员'},
        {id: 125, parentId:13,name: '地勤人员'},
        {id: 126, parentId:13,name: '列车司机'},
        {id: 127, parentId:13,name: '乘务员'},
        {id: 128, parentId:13,name: '船长'},
        {id: 129, parentId:13,name: '船员'},
        {id: 130, parentId:13,name: '司机'},
        {id: 131, parentId:13,name: '其他'},
        {id: 132, parentId:14,name: '部门领导'},
        {id: 133, parentId:14,name: '行政人员'},
        {id: 134, parentId:14,name: '法院'},
        {id: 135, parentId:14,name: '公安机关'},
        {id: 136, parentId:14,name: '军人'},
        {id: 137, parentId:14,name: '公务员'},
        {id: 138, parentId:14,name: '其他'},
        {id: 139, parentId:15,name: '教授'},
        {id: 140, parentId:15,name: '讲师/助教'},
        {id: 141, parentId:15,name: '中学教师'},
        {id: 142, parentId:15,name: '小学教师'},
        {id: 143, parentId:15,name: '幼师'},
        {id: 144, parentId:15,name: '教务管理人员'},
        {id: 145, parentId:15,name: '职业技术教师'},
        {id: 146, parentId:15,name: '培训师'},
        {id: 147, parentId:15,name: '科研管理人员'},
        {id: 148, parentId:15,name: '科研人员'},
        {id: 149, parentId:15,name: '其他'},
        {id: 150, parentId:16,name: '餐饮管理'},
        {id: 151, parentId:16,name: '厨师'},
        {id: 152, parentId:16,name: '餐厅服务员'},
        {id: 153, parentId:16,name: '酒店管理'},
        {id: 154, parentId:16,name: '大堂经理'},
        {id: 155, parentId:16,name: '酒店服务员'},
        {id: 156, parentId:16,name: '导游'},
        {id: 157, parentId:16,name: '美容师'},
        {id: 158, parentId:16,name: '健身教练'},
        {id: 159, parentId:16,name: '商场管理'},
        {id: 160, parentId:16,name: '零售店店长'},
        {id: 161, parentId:16,name: '店员'},
        {id: 162, parentId:16,name: '保安经理'},
        {id: 163, parentId:16,name: '保安人员'},
        {id: 164, parentId:16,name: '家政服务'},
        {id: 165, parentId:16,name: '其他'},
        {id: 166,  parentId:17,name: '建筑师'},
        {id: 167,  parentId:17,name: '工程师'},
        {id: 168,  parentId:17,name: '规划师'},
        {id: 169,  parentId:17,name: '景观设计'},
        {id: 170,  parentId:17,name: '房地产策划'},
        {id: 171,  parentId:17,name: '房地产交易'},
        {id: 172,  parentId:17,name: '物业管理'},
        {id: 173,  parentId:17,name: '其他'},
        {id: 174, parentId:18,name: '律师'},
        {id: 175, parentId:18,name: '律师助理'},
        {id: 176, parentId:18,name: '法务经理'},
        {id: 177, parentId:18,name: '法务专员'},
        {id: 178, parentId:18,name: '知识产权专员'},
        {id: 179, parentId:18,name: '其他'},
        {id: 180, parentId:19,name: '财务总监'},
        {id: 181, parentId:19,name: '财务经理'},
        {id: 182, parentId:19,name: '财务主管'},
        {id: 183, parentId:19,name: '会计'},
        {id: 184, parentId:19,name: '注册会计师'},
        {id: 185, parentId:19,name: '审计师'},
        {id: 186, parentId:19,name: '税务经理'},
        {id: 187, parentId:19,name: '税务专员'},
        {id: 188, parentId:19,name: '成本经理'},
        {id: 189, parentId:19,name: '其他'},
        {id: 190, parentId:20,name: '生物工程'},
        {id: 191, parentId:20,name: '药品生产'},
        {id: 192, parentId:20,name: '临床研究'},
        {id: 193, parentId:20,name: '医疗器械'},
        {id: 194, parentId:20,name: '医药代表'},
        {id: 195, parentId:20,name: '化工工程师'},
        {id: 196, parentId:20,name: '其他'},
        {id: 197, parentId:21,name: '医疗管理'},
        {id: 198, parentId:21,name: '医生'},
        {id: 199, parentId:21,name: '心理医生'},
        {id: 200, parentId:21,name: '药剂师'},
        {id: 201, parentId:21,name: '护士'},
        {id: 202, parentId:21,name: '兽医'},
        {id: 203, parentId:21,name: '其他'},
        {id: 204, parentId:22,name: '投资'},
        {id: 205, parentId:22,name: '保险'},
        {id: 206, parentId:22,name: '金融'},
        {id: 207, parentId:22,name: '银行'},
        {id: 208, parentId:22,name: '证券'},
        {id: 209, parentId:22,name: '其他'},
        {id: 210, parentId:23,name: '专业顾问'},
        {id: 211, parentId:23,name: '咨询经理'},
        {id: 212, parentId:23,name: '咨询师'},
        {id: 213, parentId:23,name: '培训师'},
        {id: 214, parentId:23,name: '其他'}
    ],

    'occupation': [
        {id: 1,name: '销售',icon: '01'},
        {id: 2,name: '计算机/互联网',icon: '03'},
        {id: 3,name: '客户服务',icon: '02'},
        {id: 4,name: '学生',icon: '22'},
        {id: 5,name: '通信/电子',icon: '04'},
        {id: 6,name: '生产/制造',icon: '05'},
        {id: 7,name: '物流/仓储',icon: '06'},
        {id: 8,name: '商贸/采购',icon: '07'},
        {id: 9,name: '人事/行政',icon: '08'},
        {id: 10,name: '高级管理',icon: '09'},
        {id: 11,name: '广告/市场',icon: '10'},
        {id: 12,name: '传媒/艺术',icon: '11'},
        {id: 13,name: '交通运输',icon: '12'},
        {id: 14,name: '政府机构',icon: '13'},
        {id: 15,name: '教育/科研',icon: '13'},
        {id: 16,name: '服务业',icon: '14'},
        {id: 17,name: '建筑/房地产',icon: '15'},
        {id: 18,name: '法律',icon: '16'},
        {id: 19,name: '财会/审计',icon: '17'},
        {id: 20,name: '生物/制药',icon: '18'},
        {id: 21,name: '医疗/护理',icon: '19'},
        {id: 22,name: '金融/银行/保险',icon: '20'},
        {id: 23,name: '咨询/顾问',icon: '21'}
    ],
    'nation': [
        {id: "1", name: '汉族'},
        {id: "2", name: '藏族'},
        {id: "3", name: '朝鲜族'},
        {id: "4", name: '蒙古族'},
        {id: "5", name: '回族'},
        {id: "6", name: '满族'},
        {id: "7", name: '维吾尔族'},
        {id: "8", name: '壮族'},
        {id: "9", name: '彝族'},
        {id: "10", name: '苗族'},
        {id: "11", name: '其他'}
    ],
    'salary': [
        {id: "1", name: '3-5万'},
        {id: "2", name: '6-9万'},
        {id: "3", name: '10-15万'},
        {id: "4", name: '16-25万'},
        {id: "5", name: '100万以上'}
    ],
    'house': [
        {id: "1", name: '已购房'},
        {id: "2", name: '未购房'}
    ],
    'car': [
        {id: "1", name: '已购车'},
        {id: "2", name: '未购车'}
    ],
    'blood': [
        {id: "1", name: 'A型'},
        {id: "2", name: 'B型'},
        {id: "3", name: 'AB型'},
        {id: "4", name: 'O型'},
        {id: "5", name: 'RH型'}
    ],
    'children': [
        {id: "1", name: '无小孩'},
        {id: "2", name: '有小孩归自己'},
        {id: "3", name: '有小孩归对方'}
    ],

    'feedback': [
        '诽谤辱骂',
        '淫秽色情',
        '血腥暴力',
        '垃圾广告',
        '欺骗（酒托、话费托等骗取行为）',
        '违法行为（涉毒、暴恐、违禁品等）',
        '冒用他人照片',
        '资料不真实'
    ],
    'label': {
        'man': [
            {name: '颜值高',hot:1},
            {name: '白富美',hot:0},
            {name: '逗逼',hot:1},
            {name: '御姐',hot:0},
            {name: '萝莉',hot:0},
            {name: '土豪',hot:0},
            {name: '女神',hot:0},
            {name: '吃货',hot:1},
            {name: '自来熟',hot:1},
            {name: '御宅族',hot:0},
            {name: '不限',hot:0}
        ],
        'woman':[
            {name:'高富帅',hot:0},
            {name:'长腿欧巴',hot:1},
            {name:'型男',hot:0},
            {name:'大叔',hot:0},
            {name:'土豪',hot:0},
            {name:'男神',hot:1},
            {name:'吃货',hot:0},
            {name:'小鲜肉',hot:1},
            {name:'逗逼',hot:1},
            {name:'自来熟',hot:1},
            {name:'御宅族',hot:0},
            {name:'暖男',hot:1},
            {name:'小公举',hot:0},
            {name:'不限',hot:0}
        ]
    },
    emoji:{
        1:'微笑',
        2:'撇嘴',
        3:'色',
        4:'发呆',
        5:'流泪',
        6:'害羞',
        7:'闭嘴',
        8:'睡',
        9:'大哭',
        10:'尴尬',
        11:'发怒',
        12:'调皮',
        13:'呲牙',
        14:'惊讶',
        15:'难过',
        16:'冷汗',
        17:'抓狂',
        18:'吐',
        19:'偷笑',
        20:'可爱',
        21:'白眼',
        22:'傲慢',
        23:'饥饿',
        24:'困',
        25:'惊恐',
        26:'流汗',
        27:'憨笑',
        28:'大兵',
        29:'奋斗',
        30:'咒骂',
        31:'疑问',
        32:'嘘',
        33:'晕',
        34:'折磨',
        35:'衰',
        36:'敲打',
        37:'再见',
        38:'擦汗',
        39:'抠鼻',
        40:'糗大了',
        41:'坏笑',
        42:'左哼哼',
        43:'右哼哼',
        44:'哈欠',
        45:'鄙视',
        46:'委屈',
        47:'快哭了',
        48:'阴险',
        49:'亲亲',
        50:'吓',
        51:'可怜',
        52:'拥抱',
        53:'月亮',
        54:'太阳',
        55:'炸弹',
        56:'骷髅',
        57:'菜刀',
        58:'猪头',
        59:'西瓜',
        60:'咖啡',
        61:'饭',
        62:'爱心',
        63:'强',
        64:'弱',
        65:'握手',
        66:'胜利',
        67:'抱拳',
        68:'勾引',
        69:'OK',
        70:'NO',
        71:'玫瑰',
        72:'凋谢',
        73:'示爱',
        74:'爱情',
        75:'飞吻',
    },
    sports:[
        {}
    ]

};

function config_heightLink(min) {
    var data = [];
    for (var i = min; i <= 260; i++) {
        data.push({
            'id': i,
            'name': i + '厘米'
        })
    }
    return data;
}
